
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.57.40:3306/dbgirl
    username: root
    password: Founder123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

